// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (user_id)
VALUES (
    $1
)
`

func (q *Queries) CreateAccount(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, createAccount, userID)
	return err
}

const disableAccount = `-- name: DisableAccount :exec
UPDATE account
SET verified = NOW()
WHERE user_id = $1
`

func (q *Queries) DisableAccount(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, disableAccount, userID)
	return err
}

const verifyAccount = `-- name: VerifyAccount :exec
UPDATE account 
SET verified = true
WHERE user_id = $1
`

func (q *Queries) VerifyAccount(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, verifyAccount, userID)
	return err
}
