// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: media.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTripMedia = `-- name: CreateTripMedia :one
INSERT INTO trip_media(trip_id, trip_stop_id, photo_url, video_url)
VALUES(
    $1,
    $2,
    $3,
    $4
)
RETURNING id, trip_id, trip_stop_id, photo_url, video_url, created_at, updated_at
`

type CreateTripMediaParams struct {
	TripID     uuid.NullUUID
	TripStopID uuid.NullUUID
	PhotoUrl   sql.NullString
	VideoUrl   sql.NullString
}

func (q *Queries) CreateTripMedia(ctx context.Context, arg CreateTripMediaParams) (TripMedium, error) {
	row := q.db.QueryRowContext(ctx, createTripMedia,
		arg.TripID,
		arg.TripStopID,
		arg.PhotoUrl,
		arg.VideoUrl,
	)
	var i TripMedium
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TripStopID,
		&i.PhotoUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTripMedia = `-- name: DeleteTripMedia :exec
DELETE FROM trip_media
WHERE id = $1
`

func (q *Queries) DeleteTripMedia(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTripMedia, id)
	return err
}

const getTripMediaById = `-- name: GetTripMediaById :one
SELECT id, trip_id, trip_stop_id, photo_url, video_url, created_at, updated_at FROM trip_media
WHERE id = $1
`

func (q *Queries) GetTripMediaById(ctx context.Context, id uuid.UUID) (TripMedium, error) {
	row := q.db.QueryRowContext(ctx, getTripMediaById, id)
	var i TripMedium
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.TripStopID,
		&i.PhotoUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripMediaByTripId = `-- name: GetTripMediaByTripId :many
SELECT id, trip_id, trip_stop_id, photo_url, video_url, created_at, updated_at FROM trip_media
WHERE trip_id = $1
`

func (q *Queries) GetTripMediaByTripId(ctx context.Context, tripID uuid.NullUUID) ([]TripMedium, error) {
	rows, err := q.db.QueryContext(ctx, getTripMediaByTripId, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripMedium
	for rows.Next() {
		var i TripMedium
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.TripStopID,
			&i.PhotoUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTripMedia = `-- name: UpdateTripMedia :exec
UPDATE trip_media
SET photo_url = $1, video_url = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateTripMediaParams struct {
	PhotoUrl sql.NullString
	VideoUrl sql.NullString
	ID       uuid.UUID
}

func (q *Queries) UpdateTripMedia(ctx context.Context, arg UpdateTripMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateTripMedia, arg.PhotoUrl, arg.VideoUrl, arg.ID)
	return err
}
