// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: trip.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    start_date,
    start_location,
    end_location,
    end_date,
    distance_travelled,
    user_id
) VALUES (
$1,
$2,
$3,
$4,
$5,
$6
)
RETURNING id, start_date, start_location, end_location, end_date, distance_travelled, created_at, updated_at, user_id
`

type CreateTripParams struct {
	StartDate         time.Time
	StartLocation     interface{}
	EndLocation       interface{}
	EndDate           sql.NullTime
	DistanceTravelled sql.NullFloat64
	UserID            uuid.UUID
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.StartDate,
		arg.StartLocation,
		arg.EndLocation,
		arg.EndDate,
		arg.DistanceTravelled,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.StartLocation,
		&i.EndLocation,
		&i.EndDate,
		&i.DistanceTravelled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips
WHERE  id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, start_date, start_location, end_location, end_date, distance_travelled, created_at, updated_at, user_id FROM trips 
WHERE user_id = $1 AND  id = $2
`

type GetTripParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetTrip(ctx context.Context, arg GetTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, arg.UserID, arg.ID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.StartLocation,
		&i.EndLocation,
		&i.EndDate,
		&i.DistanceTravelled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getTrips = `-- name: GetTrips :many
SELECT id, start_date, start_location, end_location, end_date, distance_travelled, created_at, updated_at, user_id FROM trips 
WHERE user_id = $1
`

func (q *Queries) GetTrips(ctx context.Context, userID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, getTrips, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.StartLocation,
			&i.EndLocation,
			&i.EndDate,
			&i.DistanceTravelled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET
    end_location = $1,
    end_date = $2,
    distance_travelled = $3,
    updated_at = $4
WHERE
    id = $5 
RETURNING id, start_date, start_location, end_location, end_date, distance_travelled, created_at, updated_at, user_id
`

type UpdateTripParams struct {
	EndLocation       interface{}
	EndDate           sql.NullTime
	DistanceTravelled sql.NullFloat64
	UpdatedAt         time.Time
	ID                uuid.UUID
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, updateTrip,
		arg.EndLocation,
		arg.EndDate,
		arg.DistanceTravelled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.StartLocation,
		&i.EndLocation,
		&i.EndDate,
		&i.DistanceTravelled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
