// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, updated_at) 
VALUES (
    $1,
    $2,
    $3,
    $4
) 
RETURNING id, created_at, updated_at, username, password_hash, email
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, email,password_hash, created_at
FROM USERS
WHERE username = $1 OR id = $2
`

type GetUserParams struct {
	Username string
	ID       uuid.UUID
}

type GetUserRow struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Username, arg.ID)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $1
`

func (q *Queries) UpdatePassword(ctx context.Context, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, updatePassword, passwordHash)
	return err
}

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE users
SET username = $1, email = $2, updated_at = $3
WHERE id = $1 
RETURNING id, created_at, updated_at, username, password_hash, email
`

type UpdateUserDetailsParams struct {
	Username  string
	Email     string
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails, arg.Username, arg.Email, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
	)
	return i, err
}
